/**
 * Enrich data.generated.js with Google Places ratings.
 *
 * Usage:
 *   node scripts/enrich-ratings.mjs --limit 5      # Test on first 5 unprocessed
 *   node scripts/enrich-ratings.mjs --limit 5 --dry-run   # Same, but don't write
 *   node scripts/enrich-ratings.mjs                # Full run on every unprocessed place
 *   node scripts/enrich-ratings.mjs --force        # Re-process every place
 *
 * Reads GOOGLE_PLACES_API_KEY from .env (parsed inline; no dotenv dependency).
 * Calls the Places API (New) Text Search endpoint:
 *   POST https://places.googleapis.com/v1/places:searchText
 * with a field mask that requests only id, displayName, rating, userRatingCount.
 *
 * Behavior per place:
 *   - "{name}, {city}, {country}" query string
 *   - 100ms pause between requests
 *   - Logs progress every 25 places
 *   - Writes data.generated.js every 50 successful lookups so a crash mid-run
 *     doesn't lose progress
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DATA_PATH = path.join(ROOT, "data.generated.js");
const ENV_PATH = path.join(ROOT, ".env");

const PLACES_API_URL = "https://places.googleapis.com/v1/places:searchText";
const FIELD_MASK = "places.id,places.displayName,places.rating,places.userRatingCount";
const PAUSE_MS = 100;
const SAVE_EVERY = 50;
const LOG_EVERY = 25;

/** Minimal .env parser: KEY=VALUE per line, optional quotes, ignores comments. */
function loadEnv(envPath) {
  if (!existsSync(envPath)) return {};
  const out = {};
  for (const line of readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq < 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

/** Read PLACES array from data.generated.js by JSON-parsing the [ ... ] body. */
function loadPlaces() {
  const src = readFileSync(DATA_PATH, "utf8");
  const start = src.indexOf("[");
  let depth = 0;
  let end = start;
  for (; end < src.length; end++) {
    const ch = src[end];
    if (ch === "[") depth++;
    else if (ch === "]") {
      depth--;
      if (depth === 0) {
        end++;
        break;
      }
    }
  }
  return JSON.parse(src.slice(start, end));
}

function writePlaces(places) {
  writeFileSync(
    DATA_PATH,
    "// Generated by scripts/collect.mjs. Do not edit by hand.\n" +
      `export const PLACES = ${JSON.stringify(places, null, 2)};\n`,
  );
}

function parseArgs() {
  const argv = process.argv.slice(2);
  const opts = { limit: null, dryRun: false, force: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--limit" && argv[i + 1] !== undefined) {
      opts.limit = Number(argv[++i]);
    } else if (a === "--dry-run") {
      opts.dryRun = true;
    } else if (a === "--force") {
      opts.force = true;
    }
  }
  return opts;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/**
 * Round to one decimal place. Example: 4.27 -> 4.3.
 * Preserves null for missing values.
 */
function roundRating(value) {
  if (typeof value !== "number" || Number.isNaN(value)) return null;
  return Math.round(value * 10) / 10;
}

/**
 * Call Places API Text Search and return { rating, userRatingCount, placeId }
 * or null when no clear match exists.
 *
 * Returns:
 *   { kind: "success", rating, userRatingCount, placeId }
 *   { kind: "not_found" }
 *   { kind: "error", message, status }
 */
async function lookup(place, apiKey) {
  const textQuery = `${place.name}, ${place.city}, ${place.country}`;
  try {
    const res = await fetch(PLACES_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": apiKey,
        "X-Goog-FieldMask": FIELD_MASK,
      },
      body: JSON.stringify({ textQuery, pageSize: 1 }),
    });
    if (!res.ok) {
      const text = await res.text();
      return {
        kind: "error",
        status: res.status,
        message: `HTTP ${res.status}: ${text.slice(0, 200)}`,
      };
    }
    const data = await res.json();
    const top = Array.isArray(data.places) && data.places.length > 0 ? data.places[0] : null;
    if (!top) return { kind: "not_found" };
    return {
      kind: "success",
      rating: roundRating(top.rating),
      userRatingCount: typeof top.userRatingCount === "number" ? top.userRatingCount : null,
      placeId: typeof top.id === "string" ? top.id : null,
    };
  } catch (err) {
    return {
      kind: "error",
      status: 0,
      message: err instanceof Error ? err.message : String(err),
    };
  }
}

async function main() {
  const opts = parseArgs();
  const env = loadEnv(ENV_PATH);
  const apiKey = env.GOOGLE_PLACES_API_KEY || process.env.GOOGLE_PLACES_API_KEY;
  if (!apiKey || apiKey === "PASTE_KEY_HERE") {
    console.error(
      "[enrich-ratings] No API key. Set GOOGLE_PLACES_API_KEY in .env (current value is the placeholder).",
    );
    process.exit(1);
  }

  const places = loadPlaces();
  const targets = opts.force
    ? places
    : places.filter((p) => p.ratingLookupStatus !== "success");
  const queue = opts.limit !== null ? targets.slice(0, opts.limit) : targets;

  console.log(
    `[enrich-ratings] ${places.length} total, ${targets.length} to process, running on ${queue.length}${opts.dryRun ? " (dry-run)" : ""}`,
  );

  const stats = { success: 0, not_found: 0, error: 0 };
  const errors = [];
  let touchedSinceSave = 0;

  for (let i = 0; i < queue.length; i++) {
    const target = queue[i];
    const idx = places.findIndex((p) => p.id === target.id);
    if (idx < 0) continue;

    const result = await lookup(target, apiKey);
    if (result.kind === "success") {
      places[idx] = {
        ...places[idx],
        googleRating: result.rating,
        googleRatingCount: result.userRatingCount,
        googlePlaceId: result.placeId,
        ratingLookupStatus: "success",
      };
      stats.success++;
    } else if (result.kind === "not_found") {
      places[idx] = {
        ...places[idx],
        ratingLookupStatus: "not_found",
      };
      stats.not_found++;
    } else {
      places[idx] = {
        ...places[idx],
        ratingLookupStatus: "error",
      };
      stats.error++;
      errors.push({ id: target.id, name: target.name, ...result });
      console.warn(
        `[enrich-ratings] error on "${target.name}" (${target.city}): ${result.message}`,
      );
    }
    touchedSinceSave++;

    if ((i + 1) % LOG_EVERY === 0 || i === queue.length - 1) {
      console.log(
        `Processed ${i + 1}/${queue.length}, ${stats.success} success, ${stats.not_found} not_found, ${stats.error} error`,
      );
    }
    if (!opts.dryRun && touchedSinceSave >= SAVE_EVERY) {
      writePlaces(places);
      touchedSinceSave = 0;
      console.log(`[enrich-ratings] checkpoint: wrote ${DATA_PATH}`);
    }
    if (i < queue.length - 1) await sleep(PAUSE_MS);
  }

  if (!opts.dryRun) {
    writePlaces(places);
    console.log(`[enrich-ratings] final write: ${DATA_PATH}`);
  } else {
    console.log("[enrich-ratings] dry-run: no file written");
  }

  console.log("\n=== Summary ===");
  console.log(JSON.stringify(stats, null, 2));
  if (errors.length) {
    console.log("\n=== First 10 errors ===");
    for (const e of errors.slice(0, 10)) {
      console.log(`  ${e.name} | status=${e.status} | ${e.message}`);
    }
  }

  if (opts.limit !== null) {
    console.log("\n=== Per-place detail (test run) ===");
    for (const target of queue) {
      const p = places.find((x) => x.id === target.id);
      console.log(
        `  ${p.name} (${p.city}) → status=${p.ratingLookupStatus}, rating=${p.googleRating}, count=${p.googleRatingCount}, placeId=${p.googlePlaceId}`,
      );
    }
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
