/**
 * Phase 1: Clear descriptors.
 * Phase 2: Apply ../data/category-fixes.json (category overrides).
 * Phase 3: Layered English descriptors:
 *   Layer 1 — EN Wikipedia REST summaries (translate if needed).
 *   Layer 2 — DuckDuckGo HTML search snippets (translate + shape).
 *   Layer 3 — Venue og:/meta description from website / listing URL (last resort; translate + shape).
 *
 * Parallelism: 5 concurrent workers (light jitter to ease rate limits).
 *
 * Usage: node scripts/fullRegeneratePlaces.mjs
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { isReliableAutoDescriptor, lintDescriptor } from "../descriptorSynth.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DATA = path.join(ROOT, "data.generated.js");
const FIXES = path.join(ROOT, "data/category-fixes.json");

const UA =
  "TastePlacesBot/1.0 (layered regeneration; https://github.com/kittygotclauds/taste)";
const FETCH_TIMEOUT_MS = 25_000;
const MAX_HTML_BYTES = 550_000;
const CONCURRENCY = 5;

const JUNK_URL_SUBSTR = ["happeningnext.com", "eventbrite.", "meetup.com", "ticketmaster."];

/** @typedef {{ descriptor: string; layer: 0 | 1 | 2 | 3 }} DescribeOutcome */

function loadPlacesFromGeneratedJs() {
  const t = readFileSync(DATA, "utf8");
  const start = t.indexOf("[");
  let depth = 0;
  let end = start;
  for (; end < t.length; end++) {
    const c = t[end];
    if (c === "[") depth++;
    else if (c === "]") {
      depth--;
      if (depth === 0) {
        end++;
        break;
      }
    }
  }
  return JSON.parse(t.slice(start, end));
}

function savePlaces(places) {
  const js =
    "// Generated by scripts/collect.mjs. Do not edit by hand.\n" +
    `export const PLACES = ${JSON.stringify(places, null, 2)};\n`;
  writeFileSync(DATA, js, "utf8");
}

/** @param {string} s */
function wordCount(s) {
  return (s ?? "")
    .trim()
    .split(/\s+/)
    .filter(Boolean).length;
}

/** @param {string} text @param {string} city @param {string} country */
function stripGeo(text, city, country) {
  let s = text;
  const bits = [city, country].filter(Boolean);
  for (const g of bits) {
    if (!g || g.length < 3) continue;
    const re = new RegExp(`\\b${g.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "gi");
    s = s.replace(re, "");
  }
  const first = (city ?? "").split(/\s+/)[0];
  if (first && first.length > 3) {
    const re = new RegExp(`\\b${first.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "gi");
    s = s.replace(re, "");
  }
  return s.replace(/\s+/g, " ").replace(/^[\s,.;-]+/, "").trim();
}

function parseGtxResponse(raw) {
  const anchor = '[["';
  const pos = raw.indexOf(anchor);
  if (pos === -1) return "";
  let i = pos + anchor.length;
  if (raw[i] !== '"') return "";
  i++;
  let out = "";
  while (i < raw.length) {
    const c = raw[i++];
    if (c === "\\") {
      const n = raw[i++];
      if (n === '"') out += '"';
      else if (n === "n") out += "\n";
      else out += n ?? "";
      continue;
    }
    if (c === '"') break;
    out += c;
  }
  return out;
}

/** @param {string} q */
async function translateToEn(q) {
  const text = q.trim();
  if (!text) return "";
  if (/^[\x00-\x7F]+$/.test(text)) return text;
  try {
    const u =
      "https://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=en&dt=t&q=" +
      encodeURIComponent(text.slice(0, 4000));
    const r = await fetch(u, { headers: { "User-Agent": UA } });
    const parsed = parseGtxResponse(await r.text());
    return parsed.length >= 2 ? parsed : text;
  } catch {
    return text;
  }
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

/** @param {string} url @param {string} text */
function isJunkUrl(url, text = "") {
  const u = (url ?? "").toLowerCase();
  if (JUNK_URL_SUBSTR.some((j) => u.includes(j))) return true;
  return /\b(happening at|talking about this|likes ·)\b/i.test(text ?? "");
}

/** @param {string} s */
function isBoilerplateMeta(s) {
  const t = (s ?? "").trim();
  if (!t) return true;
  if (wordCount(t) > 48) return true;
  return /\|\s*(Find all|Official|Tickets|Visit)\b|before your visit\b|cookie\b.*policy\b/i.test(t);
}

/** @param {string} html */
function stripHtmlTags(html) {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&[#a-z0-9]+;/gi, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/** @param {string} html */
function extractSnippetsFromDuck(html) {
  const parts = [];
  const patterns = [
    /<a[^>]*class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)<\/a>/gi,
    /<td[^>]*class="[^"]*result-snippet[^"]*"[^>]*>([\s\S]*?)<\/td>/gi,
    /<span[^>]*class="[^"]*snippet[^"]*"[^>]*>([\s\S]*?)<\/span>/gi,
  ];
  for (const re of patterns) {
    let m;
    while ((m = re.exec(html)) !== null) {
      const t = stripHtmlTags(m[1]);
      if (t.length > 25) parts.push(t);
    }
  }
  return [...new Set(parts)].join(" ").replace(/\s+/g, " ").trim().slice(0, 1600);
}

/** @param {string} query */
async function duckFetchSnippets(query) {
  const tries = [
    async () => {
      const ac = new AbortController();
      const to = setTimeout(() => ac.abort(), FETCH_TIMEOUT_MS);
      const r = await fetch("https://lite.duckduckgo.com/lite/?q=" + encodeURIComponent(query), {
        headers: { "User-Agent": UA, Accept: "text/html,*/*" },
        signal: ac.signal,
      });
      clearTimeout(to);
      return await r.text();
    },
    async () => {
      const ac2 = new AbortController();
      const to2 = setTimeout(() => ac2.abort(), FETCH_TIMEOUT_MS);
      const r = await fetch("https://html.duckduckgo.com/html/", {
        method: "POST",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          "User-Agent": UA,
        },
        body: new URLSearchParams({ q: query }).toString(),
        signal: ac2.signal,
      });
      clearTimeout(to2);
      return await r.text();
    },
  ];

  for (const fn of tries) {
    try {
      const html = await fn();
      const sn = extractSnippetsFromDuck(html);
      if (sn.length >= 90) return sn;
    } catch {
      /* try next */
    }
    await sleep(35 + Math.floor(Math.random() * 45));
  }
  return "";
}

/** @param {string} html */
function extractMeta(html) {
  const og =
    html.match(/property=["']og:description["'][^>]*content=["']([^"']*)["']/i) ||
    html.match(/content=["']([^"']*)["'][^>]*property=["']og:description["']/i);
  const md =
    html.match(/name=["']description["'][^>]*content=["']([^"']*)["']/i) ||
    html.match(/content=["']([^"']*)["'][^>]*name=["']description["']/i);
  return stripHtmlTags((og?.[1] ?? md?.[1] ?? "").trim());
}

/** @param {string} url */
async function fetchMetaDescription(url) {
  if (!/^https?:\/\//i.test(url ?? "")) return "";
  const ac = new AbortController();
  const to = setTimeout(() => ac.abort(), FETCH_TIMEOUT_MS);
  try {
    const r = await fetch(url, {
      signal: ac.signal,
      redirect: "follow",
      headers: {
        Accept: "text/html,application/xhtml+xml",
        "User-Agent": UA,
      },
    });
    const buf = await r.arrayBuffer();
    const slice = buf.byteLength > MAX_HTML_BYTES ? buf.slice(0, MAX_HTML_BYTES) : buf;
    const html = new TextDecoder("utf-8", { fatal: false }).decode(slice);
    return extractMeta(html);
  } catch {
    return "";
  } finally {
    clearTimeout(to);
  }
}

/** @param {string} name @param {string} city @param {string} country */
async function wikiSearchBestTitle(name, city, country) {
  const queries = [`${name} ${city}`, `${name}`, `${name} ${country}`];

  const nameTokens = name
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length > 1);

  let best = /** @type {string|null} */ (null);
  let bestScore = -1;

  for (const q of queries) {
    const url =
      "https://en.wikipedia.org/w/api.php?action=query&format=json&list=search&srsearch=" +
      encodeURIComponent(q) +
      "&srlimit=12";
    let j;
    try {
      const ac = new AbortController();
      const to = setTimeout(() => ac.abort(), FETCH_TIMEOUT_MS);
      const r = await fetch(url, { headers: { "User-Agent": UA }, signal: ac.signal });
      const body = await r.text();
      clearTimeout(to);
      j = JSON.parse(body);
    } catch {
      await sleep(80 + Math.floor(Math.random() * 120));
      continue;
    }

    const hits = j.query?.search ?? [];
    for (const h of hits) {
      const title = h.title;
      const tl = title.toLowerCase();
      if (/(disambiguation|disambig)\b/i.test(title)) continue;

      let sc = 0;
      for (const tok of nameTokens) {
        if (tl.includes(tok)) sc += tok.length > 4 ? 15 : 8;
      }
      if (tl.includes((city ?? "").toLowerCase())) sc += 10;
      const cshort = (country ?? "").toLowerCase().slice(0, 8);
      if (cshort.length > 3 && tl.includes(cshort)) sc += 5;

      if (sc > bestScore) {
        bestScore = sc;
        best = title;
      }
    }

    if (bestScore >= 22) break;
    await sleep(40);
  }

  return bestScore >= 22 ? best : null;
}

/** @param {string} title */
async function wikiSummary(title) {
  const u =
    "https://en.wikipedia.org/api/rest_v1/page/summary/" + encodeURIComponent(title.replace(/ /g, "_"));
  let j;
  try {
    const ac = new AbortController();
    const to = setTimeout(() => ac.abort(), FETCH_TIMEOUT_MS);
    const r = await fetch(u, { headers: { "User-Agent": UA }, signal: ac.signal });
    const body = await r.text();
    clearTimeout(to);
    if (!r.ok) return "";
    j = JSON.parse(body);
  } catch {
    return "";
  }
  let ex = (j.extract ?? "").replace(/\([^)]*\)/g, " ");
  if (/may refer to/i.test(ex)) return "";
  return ex.replace(/\s+/g, " ").trim();
}

/** @param {{ name: string }} place @param {string} extract */
function wikiExtractMatchesVenue(place, extract) {
  const tokens = place.name
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((w) => w.length > 2);
  if (!tokens.length) return true;
  const lower = extract.toLowerCase();
  const hits = tokens.filter((t) => lower.includes(t)).length;
  if (tokens.length >= 3) return hits >= 2;
  if (tokens.length === 2) return hits >= 2;
  return hits >= 1;
}

/** @param {{ name: string }} place @param {string} d */
function descriptorPassesVenueSanity(place, d) {
  if (!d) return false;
  const lower = d.toLowerCase();
  if (!wikiExtractMatchesVenue(place, d)) return false;
  if (/\b(of|the|in|a|an|for|with|is)\s*\.\s*$/i.test(d)) return false;
  if (/\bis a\s+[a-z.-]+\s+of\s*\.\s*$/i.test(d)) return false;
  if (/\bis a c\s*\.\s*$/i.test(d)) return false;
  if (/(^|\s)s\s+(collection|café|cafe)\b/i.test(lower)) return false;
  if (/\b(est une|des chambres|découvrez|pour votre|scientifique|gourmande|méditerranéens)\b/i.test(lower))
    return false;
  if (
    /^(discover|welcome to|welcome |step into|explore |find a point|order delicious|located inside|social class|gaza war|conference of the twenty)\b/i.test(
      lower,
    )
  )
    return false;
  if (/\b(gaza war|kiln offers private offices|conference of the twenty|social class in the)\b/i.test(lower))
    return false;
  return true;
}

/** Reject Wikipedia biography hits for venues (wrong disambiguation). */
/** @param {{ name: string; category: string }} place @param {string} ex */
function wikiExtractLooksLikeWrongBiography(place, ex) {
  const lower = ex.toLowerCase();
  if (/\bwas an american (electrical )?engineer and inventor\b/i.test(lower) && /cooper/i.test(place.name))
    return true;
  if (/\bwas a french artist\b/i.test(lower) && /rosa bonheur/i.test(place.name) && place.category === "restaurant")
    return true;
  if (/\bwas an american\b.*\binventor\b/i.test(lower) && /hewitt/i.test(place.name)) return true;
  if (/\bthe conference of the twenty two was\b/i.test(lower)) return true;
  if (/\bgaza war has had\b/i.test(lower)) return true;
  if (/\bsocial class in the\b/i.test(lower) && /the class/i.test(place.name.toLowerCase())) return true;
  if (/\bkiln offers private offices\b/i.test(lower)) return true;
  if (/château de la mercerie is located/i.test(lower)) return true;
  return false;
}

/** @param {string} str */
function isGarbage(str) {
  const l = str.toLowerCase();
  return (
    /likes ·|talking about this|could be suspended|website you are trying|dns propagation|404|page not found|access denied|could not be reached/i.test(
      l,
    ) || /\bfacebook\.com\/plugins/i.test(l)
  );
}

/** @param {string} name */
function stripNameCopulaLead(name, s) {
  const first = (name ?? "").trim().split(/\s+/)[0];
  if (!first || first.length < 3) return s;
  const esc = first.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  let t = s.replace(new RegExp(`^The ${esc}\\s+(is|was|are|were)\\s+(a|an|the)\\s+`, "i"), "");
  t = t.replace(new RegExp(`^${esc}\\s+(is|was|are|were)\\s+(a|an|the)\\s+`, "i"), "");
  return t.trim();
}

/** @param {string} s */
function stripTaxonomyPrefixes(s) {
  let t = s.trim();
  for (let i = 0; i < 6; i++) {
    const prev = t;
    t = t.replace(
      /^(Restaurant|Hotels?|Shops?|Retail stores?|Museums?|Visitor attractions?|Attractions?|Cafés?|Cafes?)\s+/i,
      "",
    );
    if (t === prev) break;
  }
  while (/^museums?\s+/i.test(t)) t = t.replace(/^museums?\s+/i, "");
  return t.trim();
}

/** @param {string} s */
function firstSentence(s) {
  const m = s.match(/^(.{20,}?[.!?])(\s|$)/);
  return m ? m[1].trim() : (s.split(/(?<=[.!?])\s+/)[0] ?? s).trim();
}

/** @param {string} extract @param {{ name: string; city: string; country: string }} place */
function shapeToDescriptor(extract, place) {
  let s = stripGeo(extract, place.city, place.country);
  s = stripNameCopulaLead(place.name, s);
  s = stripTaxonomyPrefixes(s);
  s = firstSentence(s);
  if (isGarbage(s)) return "";

  s = s.replace(/,?\s*with\s+(the\s+)?vibrant\s*\.\s*$/i, ".").trim();
  s = s.replace(/\s+\.$/, ".").trim();

  let words = s.replace(/\.$/, "").split(/\s+/).filter(Boolean);
  if (words.length > 14) words = words.slice(0, 14);
  s = words.join(" ");

  if (wordCount(s) < 8) {
    const full = stripGeo(extract, place.city, place.country);
    const parts = full.split(/(?<=[.!?])\s+/).filter(Boolean);
    if (parts[1]) {
      let tail = stripNameCopulaLead(place.name, parts[1]);
      tail = stripTaxonomyPrefixes(tail).replace(/\.$/, "");
      const extra = tail.split(/\s+/).filter(Boolean).slice(0, 8);
      const merged = (s + " " + extra.join(" ")).trim();
      const w = merged.split(/\s+/).filter(Boolean).slice(0, 14);
      s = w.join(" ");
    }
  }

  if (!/[.!?]$/.test(s)) s += ".";
  return lintDescriptor(s);
}

/** @param {string} raw @param {{ name: string; city: string; country: string }} place */
async function finalizeEnglish(raw, place) {
  if (!raw || raw.length < 40) return "";
  let en = await translateToEn(raw);
  if (isGarbage(en)) return "";
  let out = shapeToDescriptor(en, place);
  out = lintDescriptor(out);
  if (!out || !isReliableAutoDescriptor(out)) return "";
  if (!descriptorPassesVenueSanity(place, out)) return "";
  return out;
}

/** @param {{ name: string; city: string; country: string }} place */
async function layerWikipedia(place) {
  await sleep(15 + Math.floor(Math.random() * 35));
  const title = await wikiSearchBestTitle(place.name, place.city, place.country);
  if (!title) return "";
  await sleep(15 + Math.floor(Math.random() * 25));
  let ex = await wikiSummary(title);
  if (!ex || ex.length < 45 || isGarbage(ex)) return "";
  if (!wikiExtractMatchesVenue(place, ex)) return "";
  if (wikiExtractLooksLikeWrongBiography(place, ex)) return "";
  return finalizeEnglish(ex, place);
}

/** @param {{ name: string; city: string; country: string; category: string }} place */
async function layerWebSearch(place) {
  await sleep(20 + Math.floor(Math.random() * 40));
  const hints = {
    restaurant: "restaurant dining menu chef cuisine",
    hotel: "hotel lodging rooms boutique",
    shop: "shop store retail brand flagship",
    attraction: "museum gallery landmark attraction historic opera theater",
    wellness: "spa massage wellness yoga pilates clinic",
  };
  const hint = hints[place.category] ?? "travel guide";
  let blob = await duckFetchSnippets(`${place.name} ${place.city} ${hint}`);
  if (blob.length < 90) blob = await duckFetchSnippets(`${place.name} ${place.city}`);
  if (!blob || isGarbage(blob)) return "";
  return finalizeEnglish(blob, place);
}

/** @param {{ website?: string|null; placeUrl?: string }} place */
async function layerHomepage(place) {
  /** @type {string[]} */
  const urls = [];
  if (place.website && /^https?:\/\//i.test(place.website)) urls.push(place.website);
  if (place.placeUrl && /^https?:\/\//i.test(place.placeUrl)) {
    try {
      const h = new URL(place.placeUrl).hostname.replace(/^www\./, "");
      if (!/^(goop\.com|vogue\.com)$/i.test(h)) urls.push(place.placeUrl);
    } catch {
      /* skip */
    }
  }

  for (const url of urls) {
    if (isJunkUrl(url)) continue;
    await sleep(25 + Math.floor(Math.random() * 45));
    let meta = await fetchMetaDescription(url);
    if (!meta || isBoilerplateMeta(meta) || isJunkUrl(url, meta) || isGarbage(meta)) continue;
    const out = await finalizeEnglish(meta, place);
    if (out) return out;
  }
  return "";
}

/** @param {{ name: string; city: string; country: string; category: string; website?: string|null; placeUrl?: string }} place */
async function describeLayered(place) {
  try {
    let out = await layerWikipedia(place);
    if (out) return /** @type {DescribeOutcome} */ ({ descriptor: out, layer: 1 });

    out = await layerWebSearch(place);
    if (out) return /** @type {DescribeOutcome} */ ({ descriptor: out, layer: 2 });

    out = await layerHomepage(place);
    if (out) return /** @type {DescribeOutcome} */ ({ descriptor: out, layer: 3 });

    return /** @type {DescribeOutcome} */ ({ descriptor: "", layer: 0 });
  } catch (err) {
    console.warn(`[fullRegeneratePlaces] warn ${place.id}:`, err instanceof Error ? err.message : err);
    return /** @type {DescribeOutcome} */ ({ descriptor: "", layer: 0 });
  }
}

function loadCategoryFixes() {
  if (!existsSync(FIXES)) return /** @type {Record<string,string>} */ ({});
  try {
    const raw = JSON.parse(readFileSync(FIXES, "utf8"));
    const out = /** @type {Record<string,string>} */ ({});
    for (const [k, v] of Object.entries(raw)) {
      if (k.startsWith("_")) continue;
      if (typeof v === "string" && ["restaurant", "hotel", "shop", "attraction", "wellness"].includes(v)) {
        out[k] = v;
      }
    }
    return out;
  } catch {
    return {};
  }
}

/**
 * @template T
 * @param {T[]} items
 * @param {number} concurrency
 * @param {(item: T, index: number) => Promise<DescribeOutcome>} fn
 */
async function mapPool(items, concurrency, fn) {
  /** @type {DescribeOutcome[]} */
  const results = new Array(items.length);
  let next = 0;

  async function worker() {
    while (true) {
      const i = next++;
      if (i >= items.length) break;
      results[i] = await fn(items[i], i);
    }
  }

  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, () => worker()));
  return results;
}

async function main() {
  const places = loadPlacesFromGeneratedJs();
  const fixes = loadCategoryFixes();

  /** @type {{ id: string; from: string; to: string }[]} */
  const catExamples = [];

  for (const p of places) {
    p.descriptor = "";
    const f = fixes[p.id];
    if (f && f !== p.category) {
      catExamples.push({ id: p.id, from: p.category, to: f });
      p.category = f;
    }
  }

  console.log(`[fullRegeneratePlaces] Processing ${places.length} places with concurrency=${CONCURRENCY}`);

  let completed = 0;
  const outcomes = await mapPool(places, CONCURRENCY, async (p) => {
    const r = await describeLayered(p);
    completed++;
    if (completed % 25 === 0 || completed === places.length) {
      console.log(`[fullRegeneratePlaces] ${completed}/${places.length} completed`);
    }
    return r;
  });

  let layer1 = 0;
  let layer2 = 0;
  let layer3 = 0;
  let empty = 0;

  for (let i = 0; i < places.length; i++) {
    places[i].descriptor = outcomes[i].descriptor ?? "";
    switch (outcomes[i].layer) {
      case 1:
        layer1++;
        break;
      case 2:
        layer2++;
        break;
      case 3:
        layer3++;
        break;
      default:
        empty++;
        break;
    }
  }

  savePlaces(places);

  console.log("");
  console.log("=== SUMMARY ===");
  console.log(`Total places processed: ${places.length}`);
  console.log(`Descriptors written via Wikipedia (layer 1): ${layer1}`);
  console.log(`Descriptors written via web search (layer 2): ${layer2}`);
  console.log(`Descriptors written via homepage translation (layer 3): ${layer3}`);
  console.log(`Descriptors left empty: ${empty}`);
  console.log(`Category corrections applied: ${catExamples.length}`);
  if (catExamples.length) {
    console.log("Category correction examples:");
    catExamples.slice(0, 25).forEach((x) => console.log(`  ${x.id}: ${x.from} -> ${x.to}`));
  }

  const samples = [];
  const pool = [...places].filter((x) => x.descriptor);
  while (samples.length < 30 && pool.length) {
    const j = Math.floor(Math.random() * pool.length);
    samples.push(pool.splice(j, 1)[0]);
  }
  console.log("");
  console.log("Spot-check (30 random):");
  samples.forEach((p) => console.log(`  ${p.name} (${p.city}): ${p.descriptor}`));
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
