/**
 * Refresh place descriptors without re-running the full scrape or website crawl.
 * Usage: node scripts/rebuildDescriptors.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { assignDescriptors } from "../descriptorSynth.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const dataPath = path.join(ROOT, "data.generated.js");

let t = readFileSync(dataPath, "utf8");
const start = t.indexOf("[");
let depth = 0;
let end = start;
for (; end < t.length; end++) {
  const c = t[end];
  if (c === "[") depth++;
  else if (c === "]") {
    depth--;
    if (depth === 0) {
      end++;
      break;
    }
  }
}

const places = JSON.parse(t.slice(start, end));
const next = assignDescriptors(places, ROOT);
const js =
  "// Generated by scripts/collect.mjs. Do not edit by hand.\n" +
  `export const PLACES = ${JSON.stringify(next, null, 2)};\n`;
writeFileSync(dataPath, js, "utf8");
const shown = next.filter((p) => (p.descriptor ?? "").trim()).length;
console.log(`[rebuildDescriptors] ${next.length} places -> ${dataPath}`);
console.log(`[rebuildDescriptors] descriptors shown: ${shown}, omitted: ${next.length - shown}`);
